name: Build LaTeX document

on:
  push:
    branches: [ master ]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      uses: tiulpin/tectonic-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tex_path: 'main.tex'
    - name: Archive PDF
      uses: actions/upload-artifact@master
      with:
        name: main.pdf
        path: main.pdf
  
