name: Build LaTeX document

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install full TeX Live
        run: |
          sudo apt update
          sudo apt install -y texlive-full

      - name: Compile PDF
        run: |
          pdflatex main.tex
          pdflatex main.tex  # Run twice for proper rendering

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aswin_Resume
          path: main.pdf
